/*
==============================================================================
 NDOW Volunteer Portal
 Email Footer
------------------------------------------------------------------------------
 Module      : email-footer.js
 Layer       : Shared

 Responsibilities

    • Render standard NDOW email footer
    • Contact information
    • Confidentiality notice

==============================================================================
*/

export function renderEmailFooter(){

    return `

<div style="
background:#f5f7fa;
border-top:1px solid #d1d5db;
padding:28px;
font-family:Arial,sans-serif;
font-size:13px;
line-height:1.6;
color:#4b5563;
">

<div style="
font-weight:700;
font-size:15px;
color:#19304B;
margin-bottom:8px;
">

Nevada Department of Wildlife

</div>

Volunteer Portal

<br>

Event Communications System

<br><br>

This email was generated by the
NDOW Volunteer Portal regarding
your registration for a Nevada
Department of Wildlife event.

<br><br>

Please do not reply directly to this
email unless instructed by your
event coordinator.

<hr style="
margin:24px 0;
border:none;
border-top:1px solid #d1d5db;
">

<div style="
font-size:11px;
color:#6b7280;
">

<strong>CONFIDENTIALITY NOTICE</strong>

<br><br>

This email and any attachments may
contain confidential information
intended solely for the individual
or entity to whom it is addressed.
If you received this email in error,
please notify the sender immediately
and permanently delete this message.

</div>

</div>

`;

}
